Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2019-12, with the labels that each got.

#4 Fixed QT_IOLINK parameters error
  src/Device.cs
Labels: bugfix

#7 Update ReadMe.md
  doc/user_manual/images/EasyEplannerPreview.png
Labels: documentation

#10 Fixed windows behavior in add-in
  src/DFrm.cs
  src/EditorCtrl.Designer.cs
  src/EditorCtrl.cs
  src/EditorCtrl.resx
  src/ModeFrm.cs
Labels: bugfix

#13 Update documentation about M_ATV
  doc/user_manual/ReadMe.md
Labels: documentation

#15 Update synchronize function documentation
  doc/user_manual/ReadMe.md
  doc/user_manual/images/ASISynchronizeBinding.png
  doc/user_manual/images/EplanAlternativeUserFieldASI.png
  doc/user_manual/images/EplanFunctionalTextASI.png
  doc/user_manual/images/EplanFunctionalTextResultASI.png
  doc/user_manual/images/EplanUserFieldASI.png
Labels: documentation

#17 Renamed "doc" folder to "docs"
  .gitignore
  ReadMe.md
  docs/CODE_OF_CONDUCT.md
  docs/codestyle.md
  docs/contributing.md
  docs/user_manual/ReadMe.md
  docs/user_manual/UML/base_objects_s88.uxf
  docs/user_manual/UML/control_modules_s88.uxf
  docs/user_manual/images/ASISynchronizeBinding.png
  docs/user_manual/images/EasyEplannerPreview.png
  docs/user_manual/images/EplanAlternativeUserFieldASI.png
  docs/user_manual/images/EplanFunctionalTextASI.png
  docs/user_manual/images/EplanFunctionalTextResultASI.png
  docs/user_manual/images/EplanUserFieldASI.png
  docs/user_manual/images/FestoBindCircuitList.jpg
  docs/user_manual/images/FestoBindReviewList.png
  docs/user_manual/images/HA_device.png
  docs/user_manual/images/assign_channel_to_plc.png
  docs/user_manual/images/control_modules_s88.svg
  docs/user_manual/images/dev_note.png
  docs/user_manual/images/dev_supl_field_2.png
  docs/user_manual/images/dev_supl_field_3.png
  docs/user_manual/images/device_form_path.png
  docs/user_manual/images/devices_form.png
  docs/user_manual/images/edit_buttons.png
  docs/user_manual/images/edit_selected_node.png
  docs/user_manual/images/edit_selected_node_table_mode.png
  docs/user_manual/images/extra_oper_params.png
  docs/user_manual/images/functional_text_display_example.png
  docs/user_manual/images/functional_text_example.png
  docs/user_manual/images/higlight_dev.png
  docs/user_manual/images/operations_descr.png
  docs/user_manual/images/operations_descr_in_eplan.png
  docs/user_manual/images/restrictions.png
  docs/user_manual/images/s88_objects.svg
  docs/user_manual/images/select_node.png
  docs/user_manual/images/selected_restrictions.png
  docs/user_manual/images/set_base_object.png
  docs/user_manual/images/set_base_oper.png
  docs/user_manual/images/techobject_descr.png
  docs/user_manual/images/transition_between_operations.png
  docs/user_manual/images/work_with_fields_s88_ao.jpg
Labels: documentation

#16 Added IO-Link_DO1_DI2 valve
  docs/user_manual/ReadMe.md
  src/Device.cs
Labels: enhancement

#11 Update function synchronization names and modules
  src/DFrm.cs
  src/Device.cs
  src/IO.cs
  src/ProjectManager.cs
  src/main.cs
Labels: enhancement

#21 Rename slack channel
  ReadMe.md
  docs/contributing.md
Labels: documentation

#19 Относительные ссылки
  ReadMe.md
Labels: documentation, enhancement, good first issue

#25 Fixed empty LUA table error
  src/TechObject.cs
Labels: bugfix

#24 Fixed devices window error
  src/DFrm.Designer.cs
  src/DFrm.cs
  src/EProjectManager.cs
Labels: bugfix

#27 Improving get subtype function
  src/Device.cs
Labels: bugfix

#32 Исправлены орфографические ошибки
  docs/user_manual/ReadMe.md
Labels: bugfix, documentation
