Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2020-04, with the labels that each got.

#265 Added CIP_WASH_END property to POU
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseObjectProperties.cs
  src/DataBaseImitation/BaseOperations.cs
  src/TechObject/Base/TechObjects/BasePOU.cs
Labels: enhancement

#268 Renamed 'Бачок' to 'Бачок откачки лёдводы'
  docs/user_manual/ReadMe.md
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
Labels: enhancement

#261 Added ability to use aggregates in apparats
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseAggregatesProperties.cs
  src/DataBaseImitation/BaseObjectProperties.cs
  src/DataBaseImitation/BaseObjectsEquipment.cs
  src/DataBaseImitation/BaseOperationSteps.cs
  src/DataBaseImitation/BaseOperations.cs
  src/DataBaseImitation/BaseOperationsParams.cs
  src/EasyEPlanner.csproj
  src/Editor.cs
  src/EditorCtrl.cs
  src/FileSavers/PrgLuaSaver.cs
  src/Lua/sys.lua
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/TechObjects/BaseAutomat.cs
  src/TechObject/Base/TechObjects/BaseBoiler.cs
  src/TechObject/Base/TechObjects/BaseCooler.cs
  src/TechObject/Base/TechObjects/BaseCoolerPID.cs
  src/TechObject/Base/TechObjects/BaseFlowNodePID.cs
  src/TechObject/Base/TechObjects/BaseHeater.cs
  src/TechObject/Base/TechObjects/BaseHeaterPID.cs
  src/TechObject/Base/TechObjects/BaseLine.cs
  src/TechObject/Base/TechObjects/BaseLineIn.cs
  src/TechObject/Base/TechObjects/BaseLineOut.cs
  src/TechObject/Base/TechObjects/BaseMaster.cs
  src/TechObject/Base/TechObjects/BaseMixer.cs
  src/TechObject/Base/TechObjects/BasePOU.cs
  src/TechObject/Base/TechObjects/BasePost.cs
  src/TechObject/Base/TechObjects/BasePressurePID.cs
  src/TechObject/Base/TechObjects/BaseTank.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
  src/TechObject/Mode.cs
  src/TechObject/ModesManager.cs
  src/TechObject/Step.cs
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#271 Added equipment for PIDs and its checking
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseObjectsEquipment.cs
  src/Properties/AssemblyInfo.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Equipment.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#275 New saving algorithm for parameters
  src/TechObject/Base/TechObjects/BaseLine.cs
  src/TechObject/Base/TechObjects/BaseLineIn.cs
  src/TechObject/Base/TechObjects/BaseLineOut.cs
  src/TechObject/Base/TechObjects/BasePOU.cs
  src/TechObject/Base/TechObjects/BaseTank.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
  src/TechObject/Base/TechObjects/BaseWaterTankPID.cs
Labels: bugfix

#273 Corrected finding and saving base operations
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Mode.cs
  src/TechObject/Step.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#280 Added steps for objects
  src/DataBaseImitation/BaseObjectProperties.cs
  src/DataBaseImitation/BaseOperationSteps.cs
  src/DataBaseImitation/BaseOperations.cs
  src/FileSavers/PrgLuaSaver.cs
  src/TechObject/Base/TechObjects/BaseCoolerPID.cs
  src/TechObject/Base/TechObjects/BaseHeater.cs
  src/TechObject/Base/TechObjects/BaseHeaterPID.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
  src/TechObject/Base/TechObjects/BaseWaterTankPID.cs
Labels: enhancement

#282 Updated documentation about steps
  docs/user_manual/ReadMe.md
Labels: documentation

#283 Added wash request parameter
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseObjectProperties.cs
  src/DataBaseImitation/BaseOperationsParams.cs
Labels: enhancement

#287 Fixed XML export error
  src/FileSavers/XMLReporter.cs
  src/FileSavers/XMLReporterDialog.cs
  src/ProjectManager.cs
Labels: bugfix

#277 Restart edit mode after page changes
  src/EProjectManager.cs
Labels: bugfix

#285 Moved new modules and old modules to file
  docs/user_manual/ReadMe.md
  src/DeviceBindFromForm.cs
  src/EasyEPlanner.csproj
  src/IO.cs
  src/IOReader.cs
  src/Lua/sys_io.lua
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement

#290 Fixed attached objects error
  src/TechObject/TechObject.cs
Labels: bugfix

#291 Fixed error after attaching to unit
  src/TechObject/TechObject.cs
Labels: bugfix

#294 Corrected sys_io.lua
  src/Lua/sys_io.lua
Labels: bugfix

#295 Added NEED_STORING_AFTER parameter to tank
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseObjectProperties.cs
  src/DataBaseImitation/BaseOperations.cs
  src/DataBaseImitation/BaseOperationsParams.cs
Labels: enhancement

#297 Added parameters for pressure node and flow node
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseAggregatesProperties.cs
  src/DataBaseImitation/BaseOperations.cs
  src/TechObject/Base/TechObjects/BaseFlowNodePID.cs
  src/TechObject/Base/TechObjects/BasePressurePID.cs
Labels: enhancement

#299 Added "Work" base operation to base lines
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseOperationSteps.cs
  src/DataBaseImitation/BaseOperations.cs
Labels: enhancement

#302 Fixed error in XML export
  src/FileSavers/XMLReporterDialog.cs
Labels: bugfix

#171 Refactored Device.cs
  src/Device.cs
  src/Device/Device.cs
  src/Device/DeviceManager.cs
  src/Device/DeviceSubTypeEnum.cs
  src/Device/DeviceTypeEnum.cs
  src/Device/IODevice.cs
  src/Device/IODevices/AI.cs
  src/Device/IODevices/AO.cs
  src/Device/IODevices/DI.cs
  src/Device/IODevices/DO.cs
  src/Device/IODevices/FQT.cs
  src/Device/IODevices/FS.cs
  src/Device/IODevices/GS.cs
  src/Device/IODevices/HA.cs
  src/Device/IODevices/HL.cs
  src/Device/IODevices/LS.cs
  src/Device/IODevices/LT.cs
  src/Device/IODevices/M.cs
  src/Device/IODevices/PT.cs
  src/Device/IODevices/QT.cs
  src/Device/IODevices/SB.cs
  src/Device/IODevices/TE.cs
  src/Device/IODevices/V.cs
  src/Device/IODevices/VC.cs
  src/Device/IODevices/WT.cs
  src/Device/IODevices/Y(DEV_VTUG).cs
  src/EasyEPlanner.csproj
  src/FileSavers/Excel/ExcelDataCollector.cs
Labels: enhancement

#304 Saving device article to main.io file
  src/Device/IODevice.cs
Labels: enhancement

#306 Corrected encoding sys_io.lua
  src/Lua/sys_io.lua
Labels: bugfix

#185 Improving devices
  docs/user_manual/ReadMe.md
  src/Device/DeviceManager.cs
  src/Device/IODevice.cs
  src/Device/IODevices/LS.cs
  src/Device/IODevices/LT.cs
  src/Device/IODevices/PT.cs
  src/Device/IODevices/QT.cs
  src/Device/IODevices/TE.cs
  src/Device/IODevices/V.cs
  src/Device/IODevices/Y(DEV_VTUG).cs
  src/EasyEPlanner.csproj
  src/FileSavers/Excel/ExcelDataCollector.cs
  src/FileSavers/Excel/ExcelRepoter.cs
  src/IO.cs
  src/Lua/sys_iolink_devices.lua
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement

#300 Corrected idle module algorithm
  src/IdleModule.cs
Labels: bugfix

#308 Changed original assembly path to executing assembly path
  src/Device/DeviceManager.cs
Labels: enhancement

#309 Added unit-tests for io devices
  EasyEplanner.Tests/Device.Test/IODevice.Test/AI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/AO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FQT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/GS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HA.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HL.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/M.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/PT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/QT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/SB.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/TE.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/V.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/VC.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/WT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/Y(DEV_VTUG).Test.cs
  EasyEplanner.Tests/EasyEplanner.Tests.csproj
  src/EasyEPlanner.sln
Labels: enhancement

#310 Unit-tests for device class
  EasyEplanner.Tests/Device.Test/Device.Test.cs
Labels: enhancement

#313 Corrected path to sys_io.lua
  src/IO.cs
Labels: enhancement

#315 Corrected sys.io.lua
  src/Lua/sys_io.lua
Labels: bugfix

#311 Added unit tests for IODevice.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test.cs
Labels: enhancement

#316 Added unit-tests for DeviceManager.cs
  EasyEplanner.Tests/Device.Test/DeviceManager.Test.cs
  EasyEplanner.Tests/EasyEplanner.Tests.csproj
  src/Device/DeviceManager.cs
Labels: enhancement

#318 Refactored main.cs
  src/EasyEPlanner.csproj
  src/Main/AboutProgrammAction.cs
  src/Main/AddInModule.cs
  src/Main/BindingSynchronizationAction.cs
  src/Main/ExportTechDevsToExcelAction.cs
  src/Main/LoadDescriptionAction.cs
  src/Main/SaveAsXMLAction.cs
  src/Main/SaveDescriptionAction.cs
  src/Main/ShowDevicesAction.cs
  src/Main/ShowOperationsAction.cs
  src/Main/ShowTechObjectsAction.cs
  src/ModulesBindingUpdater.cs
  src/ProjectManager.cs
Labels: enhancement

#320 Refactored IO.cs
  src/EasyEPlanner.csproj
  src/IO.cs
  src/IO/IOLinkCalculator.cs
  src/IO/IOManager.cs
  src/IO/IOModule.cs
  src/IO/IOModuleInfo.cs
  src/IO/IONode.cs
Labels: enhancement

#322 Always set NameEplan field in UpperCase
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#324 Renaming equipment after replacing in object
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: bugfix

#326 Corrected parameters enumeration for saving
  src/Device/IODevices/LT.cs
Labels: bugfix

#327 Unit-tests for devices parameters sequence
  EasyEplanner.Tests/Device.Test/IODevice.Test/AI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/AO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FQT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/GS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HA.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HL.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/M.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/PT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/QT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/SB.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/TE.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/V.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/VC.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/WT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/Y(DEV_VTUG).Test.cs
  src/Device/IODevice.cs
Labels: enhancement

#329 Update Readme.md
  ReadMe.md
Labels: documentation

#331 Deleting aggregate binding to unit before deleting aggregate
  src/TechObject/TechObjectManager.cs
Labels: bugfix
