Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2020-05, with the labels that each got.

#335 Fixed special case after deleting device from scheme
  src/TechObject/Action.cs
Labels: bugfix

#338 New sorting algorithm in devices window
  src/DFrm.cs
Labels: enhancement

#340 Correcting device binding
  src/Device/IODevice.cs
  src/DeviceBindFromForm.cs
Labels: enhancement

#341 Corrected Excel export
  src/IO/IOModule.cs
Labels: enhancement

#343 Added unit-tests for devices channels
  EasyEplanner.Tests/Device.Test/IODevice.Test/AI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/AO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FQT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/GS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HA.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HL.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/M.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/PT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/QT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/SB.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/TE.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/V.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/VC.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/WT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/Y(DEV_VTUG).Test.cs
Labels: enhancement

#345 Added new base operation "Slow heat" to Tank
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseOperationSteps.cs
  src/DataBaseImitation/BaseOperations.cs
  src/TechObject/Base/TechObjects/BaseTank.cs
Labels: enhancement

#346 Fixed error after deleting object when highlighting enabled
  src/EditorCtrl.cs
Labels: bugfix

#348 Added base operation "Work" to base object "Tank"
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseOperationSteps.cs
  src/DataBaseImitation/BaseOperations.cs
Labels: enhancement

#358 Using heater node in units as property
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseAggregatesProperties.cs
  src/EasyEPlanner.csproj
  src/Properties/AssemblyInfo.cs
  src/TechObject/Base/TechObjects/BaseHeater.cs
  src/TechObject/Base/TechObjects/BaseHeaterPID.cs
  src/TechObject/Base/TechObjects/BaseTank.cs
Labels: enhancement

#357 Implemented base Boiler object
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseAggregatesProperties.cs
  src/DataBaseImitation/BaseOperationSteps.cs
  src/DataBaseImitation/BaseOperations.cs
  src/TechObject/Base/TechObjects/BaseBoiler.cs
Labels: enhancement

#359 Added new buttons to Editor form
  docs/user_manual/ReadMe.md
  docs/user_manual/images/techobject_descr.png
  src/EasyEPlanner.csproj
  src/EditorCtrl.Designer.cs
  src/EditorCtrl.cs
  src/EditorCtrl.resx
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/Resources/copy.png
  src/Resources/create.png
  src/Resources/delete.png
  src/Resources/edit1.png
  src/Resources/paste.png
  src/Resources/refresh1.png
  src/Resources/replace.png
  src/TechObject/Param.cs
Labels: enhancement

#360 Warning before deleting object
  src/Editor.cs
  src/EditorCtrl.cs
  src/TechObject/Mode.cs
  src/TechObject/Params.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#361 Fixed bug with device replacing afrer synchronizing
  src/DeviceSynchronizer.cs
  src/TechObject/Action.cs
Labels: bugfix

#363 Corrected channels addresses out for 2688084
  src/Lua/sys_io.lua
Labels: bugfix

#367 Reset attaching objects after changing base object
  src/TechObject/TechObject.cs
Labels: enhancement, review

#362 Moved base functionality to lua files
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseAggregatesProperties.cs
  src/DataBaseImitation/BaseObjectProperties.cs
  src/DataBaseImitation/BaseObjects.cs
  src/DataBaseImitation/BaseObjectsEquipment.cs
  src/DataBaseImitation/BaseOperationSteps.cs
  src/DataBaseImitation/BaseOperations.cs
  src/DataBaseImitation/BaseOperationsParams.cs
  src/Device/DeviceManager.cs
  src/EasyEPlanner.csproj
  src/Editor.cs
  src/EditorCtrl.cs
  src/FileSavers/PrgLuaSaver.cs
  src/IO/IOManager.cs
  src/Lua/sys_base_objects_description.lua
  src/Lua/sys_base_objects_initializer.lua
  src/ProjectManager.cs
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/TechObject/Base/BaseObjectsManager.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseParameter.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/Properties/ActiveBoolParameter.cs
  src/TechObject/Base/Properties/ActiveParameter.cs
  src/TechObject/Base/Properties/NonShowedProperty.cs
  src/TechObject/Base/TechObjects/BaseAutomat.cs
  src/TechObject/Base/TechObjects/BaseBoiler.cs
  src/TechObject/Base/TechObjects/BaseCooler.cs
  src/TechObject/Base/TechObjects/BaseCoolerPID.cs
  src/TechObject/Base/TechObjects/BaseFlowNodePID.cs
  src/TechObject/Base/TechObjects/BaseHeater.cs
  src/TechObject/Base/TechObjects/BaseHeaterPID.cs
  src/TechObject/Base/TechObjects/BaseLine.cs
  src/TechObject/Base/TechObjects/BaseLineIn.cs
  src/TechObject/Base/TechObjects/BaseLineOut.cs
  src/TechObject/Base/TechObjects/BaseMaster.cs
  src/TechObject/Base/TechObjects/BaseMixer.cs
  src/TechObject/Base/TechObjects/BasePOU.cs
  src/TechObject/Base/TechObjects/BasePost.cs
  src/TechObject/Base/TechObjects/BasePressurePID.cs
  src/TechObject/Base/TechObjects/BaseTank.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
  src/TechObject/Base/TechObjects/BaseWaterTankPID.cs
  src/TechObject/Equipment.cs
  src/TechObject/Step.cs
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#372 Added product_request parameter to Pressure node PID
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement, review

#370 Added steam blast node
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#371 Added sterile air node
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#374 Added tank base operation "Addition of starter"
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#369 Import/Export objects
  docs/user_manual/ReadMe.md
  docs/user_manual/images/exportObjectsForm.png
  docs/user_manual/images/importTechObjectsForm.png
  docs/user_manual/images/loadImportedObjectsForm.png
  docs/user_manual/images/loadImportedObjectsFormAfterImport.png
  docs/user_manual/images/saveExportObjectsForm.png
  docs/user_manual/images/techobject_descr.png
  src/EasyEPlanner.csproj
  src/Editor/Editor.cs
  src/Editor/EditorCtrl.Designer.cs
  src/Editor/EditorCtrl.cs
  src/Editor/EditorCtrl.resx
  src/Editor/TechObjectsExportForm.Designer.cs
  src/Editor/TechObjectsExportForm.cs
  src/Editor/TechObjectsExportForm.resx
  src/Editor/TechObjectsExporter.cs
  src/Editor/TechObjectsImportForm.Designer.cs
  src/Editor/TechObjectsImportForm.cs
  src/Editor/TechObjectsImportForm.resx
  src/Editor/TechObjectsImporter.cs
  src/EditorCtrl.resx
  src/FileSavers/ProjectDescriptionSaver.cs
  src/Lua/sys.lua
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/Resources/export.png
  src/Resources/import.png
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement, review

#379 Added info how to set up steps in queue
  docs/user_manual/ReadMe.md
Labels: enhancement, review

#377 Added error if io modules are duplicated
  src/IOReader.cs
Labels: enhancement, review

#375 Not saving empty parameters and equipment
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseParameter.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Equipment.cs
Labels: enhancement, review

#382 Corrected manual binding
  src/Device/IODevice.cs
Labels: bugfix, review

#384 Reset attached objects before import
  docs/user_manual/ReadMe.md
  src/Editor/TechObjectsImporter.cs
Labels: bugfix

#385 Import export object improvement
  EasyEplanner.Tests/Device.Test/DeviceManager.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/DeviceManager.cs
  src/Editor/Editor.cs
  src/Editor/EditorCtrl.cs
  src/Editor/TechObjectsImporter.cs
  src/TechObject/Action.cs
  src/TechObject/Step.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement, review
