Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2020-07, with the labels that each got.

#454 Added counter to heater node
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#458 Added mixing node parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#461 Added heater node parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#463 Added slow heating operation parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#462 Added boiler parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#466 Fixed copy BaseOperation error
  src/Device/IODevice.cs
  src/TechObject/Base/BaseOperation.cs
Labels: bugfix

#467 Fixed hatch description
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: bugfix

#468 Corrected calculating IO-Link in Excel
  src/Device/DeviceManager.cs
  src/Device/IODevice.cs
  src/Device/IODevices/Y(DEV_VTUG).cs
  src/IO/IOModule.cs
  src/Lua/sys_iolink_devices.lua
Labels: bugfix

#469 Added cooler node parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#470 Export mode states to Excel
  src/FileSavers/Excel/ExcelDataCollector.cs
  src/TechObject/Action.cs
  src/TechObject/State.cs
  src/TechObject/Step.cs
Labels: enhancement

#472 Corrected automatic equipment bind
  src/TechObject/Equipment.cs
Labels: enhancement

#473 Sort from A to Z in equipment
  src/TechObject/Equipment.cs
Labels: enhancement

#474 Added cooling before leavening operation parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#478 Fixed copy States error
  src/TechObject/Mode.cs
  src/TechObject/State.cs
Labels: bugfix

#479 Resize first column after expand or collapse item in tree
  src/Editor/EditorCtrl.Designer.cs
  src/Editor/EditorCtrl.cs
  src/Editor/EditorCtrl.resx
Labels: enhancement

#475 Updating XML channels base export
  EasyEplanner.Tests/Device.Test/IODevice.Test/AI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/M.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/V.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/IODevices/AI.cs
  src/Device/IODevices/LS.cs
  src/Device/IODevices/M.cs
  src/Device/IODevices/V.cs
  src/FileSavers/XMLReporter.cs
  src/Lua/sys_base_objects_description.lua
  src/Lua/sys_base_objects_initializer.lua
  src/TechObject/Base/BaseObjectsManager.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#457 Исправление ошибок в документации
  docs/user_manual/ReadMe.md
Labels: documentation

#481 Corrected autofit rows and columns in Excel
  src/FileSavers/Excel/ExcelRepoter.cs
Labels: bugfix

#482 Corrected version to actual state
  src/Properties/AssemblyInfo.cs
Labels: bugfix

#483 Corrected documentation about ModbucTCP Exchange
  docs/user_manual/InterprojectExchange.md
Labels: documentation

#485 Fixed copy and replace errors
  src/Editor/Editor.cs
  src/Editor/EditorCtrl.cs
  src/TechObject/Mode.cs
  src/TechObject/ModesManager.cs
Labels: bugfix

#487 Added cooling after souring parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#489 Updated interproject exchange with ModbusTCP
  docs/user_manual/InterprojectExchange.md
  src/InterprojectExchange/Forms/InterprojectExchangeForm.Designer.cs
  src/InterprojectExchange/Forms/PACSettingsForm.cs
Labels: enhancement

#490 Added air node sterilization operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#491 Changed cooling after souring operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#486 Added virtual devices to devices window
  src/DFrm.cs
  src/EProjectManager.cs
  src/Editor/EditorCtrl.cs
Labels: enhancement

#492 Changed slow heating operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#495 Checking project through CMD
  docs/user_manual/ReadMe.md
  src/CMD/TestLuaAvailability.txt
  src/CMD/TestProjectScript.txt
  src/Configuration/ConfigurationChecker.cs
  src/Configuration/DeviceBindingReader.cs
  src/Configuration/DeviceReader.cs
  src/Configuration/DeviceSynchronizer.cs
  src/Configuration/IOReader.cs
  src/Configuration/ProjectConfiguration.cs
  src/Configuration/ProjectHealthChecker.cs
  src/EasyEPlanner.csproj
  src/ProjectManager.cs
Labels: enhancement

#496 Added flowmeter to the lines
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#502 Deleted unused tank equipment
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#500 Automatic correction attached objects when object was deleted
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#501 Deleted obsolete items
  docs/user_manual/ReadMe.md
  docs/user_manual/images/TechObjectOperationNumbersParameter.jpg
  docs/user_manual/images/TechObjectOperationSetUpNumbers.jpg
  docs/user_manual/images/TechObjectParameters.jpg
  docs/user_manual/images/TechObjectSetUpParametersIntoOperation.jpg
  src/EasyEPlanner.csproj
  src/Editor/Editor.cs
  src/Editor/EditorCtrl.Designer.cs
  src/Editor/EditorCtrl.resx
  src/FileSavers/Excel/ExcelDataCollector.cs
  src/Lua/sys.lua
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/Resources/equipment.ico
  src/Resources/equipment.png
  src/Resources/timers.ico
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Equipment.cs
  src/TechObject/OperationParams.cs
  src/TechObject/Param.cs
  src/TechObject/ParamProperty.cs
  src/TechObject/Params.cs
  src/TechObject/ParamsManager.cs
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
  src/TechObject/TimersManager.cs
Labels: enhancement

#504 Corrected export and import objects
  src/Editor/TechObjectsExportForm.Designer.cs
  src/Editor/TechObjectsExporter.cs
  src/Editor/TechObjectsImportForm.Designer.cs
Labels: bugfix, enhancement

#494 Исправление ошибок в тесте
  docs/user_manual/test/readme.md
Labels: documentation

#505 Button for show only filled items in tree
  docs/user_manual/ReadMe.md
  docs/user_manual/images/techobject_descr.png
  src/EasyEPlanner.csproj
  src/Editor/Editor.cs
  src/Editor/EditorCtrl.Designer.cs
  src/Editor/EditorCtrl.cs
  src/Editor/EditorCtrl.resx
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/Resources/hideEmptyItems.png
  src/TechObject/Action.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/Properties/ActiveParameter.cs
  src/TechObject/Equipment.cs
  src/TechObject/Mode.cs
  src/TechObject/ModesManager.cs
  src/TechObject/OperationParams.cs
  src/TechObject/Params.cs
  src/TechObject/Restriction.cs
  src/TechObject/RestrictionManager.cs
  src/TechObject/State.cs
  src/TechObject/Step.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#508 Added hatch sensors
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#509 Read more than one device in equipment
  EasyEplanner.Tests/Device.Test/DeviceManager.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/DeviceManager.cs
  src/StaticHelper.cs
  src/TechObject/Action.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Equipment.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#512 Error when required properties in Unit are not filled
  src/Editor/Editor.cs
  src/Editor/EditorCtrl.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Mode.cs
Labels: enhancement

#511 Fixed useless whitespaces after add device in equipment
  src/EProjectManager.cs
Labels: bugfix

#513 Fixed error with set up restrictions in objects with equal type
  src/TechObject/LocalRestriction.cs
Labels: bugfix

#515 Fixed pattern for main.plua
  src/Lua/mainPattern.plua
Labels: bugfix

#516 Fixed WAGO modules addresses description
  src/Lua/sys_io.lua
Labels: bugfix
