Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2020-02, with the labels that each got.

#111 Enabled editing lines into attached objects
  docs/user_manual/ReadMe.md
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#104 Corrected channel base XML export
  src/Device.cs
  src/ProjectManager.cs
Labels: enhancement

#112 Adding parameters into operation after setting operation parameter
  docs/user_manual/ReadMe.md
  docs/user_manual/images/TechObjectOperationNumbersParameter.jpg
  docs/user_manual/images/TechObjectOperationParameters.jpg
  docs/user_manual/images/TechObjectOperationSetUpNumbers.jpg
  docs/user_manual/images/TechObjectParameters.jpg
  docs/user_manual/images/TechObjectSetUpParametersIntoOperation.jpg
  src/EasyEPlanner.csproj
  src/EditorCtrl.cs
  src/Lua/sys.lua
  src/ModeFrm.cs
  src/StaticHelper.cs
  src/TechObject/ModesManager.cs
  src/TechObject/OperationParam.cs
  src/TechObject/OperationParams.cs
  src/TechObject/Param.cs
  src/TechObject/ParamProperty.cs
  src/TechObject/Restriction.cs
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#114 Fixed incorrect input error
  src/TechObject/ParamProperty.cs
Labels: bugfix

#117 Fixed copying error
  src/DBImitation/Imitation.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Mode.cs
  src/TechObject/TechObject.cs
Labels: bugfix

#118 Fixed modyfing devices name error
  src/TechObject/Action.cs
  src/TechObject/Action_WashSeats.cs
Labels: bugfix

#122 Modify Excel output
  src/ExcelRepoter.cs
  src/TechObject/Param.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#120 Added new text comments into saving main.restrictions.lua
  src/TechObject/ModesManager.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#94 Improving base functionality
  src/DBImitation/Imitation.cs
  src/DBImitation/LineOperations.cs
  src/DBImitation/ObjectProperties.cs
  src/DBImitation/OperationsParams.cs
  src/DBImitation/TankOperations.cs
  src/EasyEPlanner.csproj
  src/Editor.cs
  src/EditorCtrl.cs
  src/StaticHelper.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseOperationProperty.cs
  src/TechObject/Base/BaseProperty.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/Properties/NonShowedProperty.cs
  src/TechObject/Base/Properties/ShowedProperty.cs
  src/TechObject/Base/TechObjects/BaseAutomat.cs
  src/TechObject/Base/TechObjects/BaseBoiler.cs
  src/TechObject/Base/TechObjects/BaseCooler.cs
  src/TechObject/Base/TechObjects/BaseHeater.cs
  src/TechObject/Base/TechObjects/BaseLine.cs
  src/TechObject/Base/TechObjects/BaseLineIn.cs
  src/TechObject/Base/TechObjects/BaseLineOut.cs
  src/TechObject/Base/TechObjects/BaseMaster.cs
  src/TechObject/Base/TechObjects/BaseMixer.cs
  src/TechObject/Base/TechObjects/BasePOU.cs
  src/TechObject/Base/TechObjects/BasePost.cs
  src/TechObject/Base/TechObjects/BaseTank.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
  src/TechObject/Mode.cs
  src/TechObject/ModesManager.cs
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#125 Created new list in Excel export
  src/Device.cs
  src/EProjectManager.cs
  src/EasyEPlanner.csproj
  src/ExcelDataCollector.cs
  src/ExcelRepoter.cs
  src/IO.cs
  src/ProjectManager.cs
  src/TechObject/ParamsManager.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#131 Fixed export channel base to scada
  src/Device.cs
  src/ProjectManager.cs
Labels: enhancement

#129 Добавлен индекс объекта
  src/TechObject/TechObject.cs
Labels: enhancement

#133 Fixed error copying operation parameters
  src/ExcelDataCollector.cs
  src/TechObject/Mode.cs
  src/TechObject/OperationParams.cs
  src/TechObject/Params.cs
  src/TechObject/ParamsManager.cs
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: bugfix

#137 Fixed displaying error
  src/EditorCtrl.cs
Labels: bugfix

#134 Added equipment to tech object
  docs/user_manual/ReadMe.md
  docs/user_manual/images/baseEquipment.png
  src/DBImitation/BaseOperationsDB.cs
  src/DBImitation/Imitation.cs
  src/DBImitation/LineOperations.cs
  src/DBImitation/ObjectProperties.cs
  src/DBImitation/OperationsParams.cs
  src/DBImitation/TankOperations.cs
  src/DBImitation/TechObjectsEquipmentDB.cs
  src/EasyEPlanner.csproj
  src/Lua/sys.lua
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/TechObjects/BaseAutomat.cs
  src/TechObject/Base/TechObjects/BaseBoiler.cs
  src/TechObject/Base/TechObjects/BaseCooler.cs
  src/TechObject/Base/TechObjects/BaseHeater.cs
  src/TechObject/Base/TechObjects/BaseLine.cs
  src/TechObject/Base/TechObjects/BaseLineIn.cs
  src/TechObject/Base/TechObjects/BaseLineOut.cs
  src/TechObject/Base/TechObjects/BaseMaster.cs
  src/TechObject/Base/TechObjects/BaseMixer.cs
  src/TechObject/Base/TechObjects/BasePOU.cs
  src/TechObject/Base/TechObjects/BasePost.cs
  src/TechObject/Base/TechObjects/BaseTank.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
  src/TechObject/Equipment.cs
  src/TechObject/ModesManager.cs
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#141 Fixes switching off highlighting
  src/EditorCtrl.cs
  src/ProjectManager.cs
Labels: bugfix

#139 Added LT to mixer node equipment
  src/DBImitation/TechObjectsEquipmentDB.cs
Labels: enhancement

#145 Hidden editable operation in the list of operations
  src/ModeFrm.cs
Labels: enhancement

#142 Creating idle application module
  src/EProjectManager.cs
  src/EasyEPlanner.csproj
  src/IdleForm.Designer.cs
  src/IdleForm.cs
  src/IdleForm.resx
  src/IdleModule.cs
  src/PInvokeUtil.cs
Labels: enhancement

#147 Intervals is fixed
  src/IdleModule.cs
Labels: bugfix

#149 Заменены символы табуляции на 4 пробела.
  src/TechObject/TechObjectManager.cs
Labels: bugfix

#148 Synchronizing restrictions in object
  src/EasyEPlanner.csproj
  src/TechObject/LocalRestriction.cs
  src/TechObject/NextModeRestriction.cs
  src/TechObject/Restriction.cs
  src/TechObject/RestrictionManager.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#152 Fixed hotkeys bug
  src/EditorCtrl.cs
  src/PInvokeUtil.cs
  src/TechObject/Restriction.cs
Labels: bugfix

#160 Updated info about XML export for SCADA
  docs/user_manual/ReadMe.md
Labels: documentation

#159 Fixed excel automatic report
  docs/user_manual/ReadMe.md
  src/EProjectManager.cs
  src/ExcelRepoter.cs
  src/ProjectManager.cs
Labels: bugfix, documentation

#156 Fixed displaying states error
  src/TechObject/State.cs
Labels: bugfix
