Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2020-10, with the labels that each got.

#556 [doc] Describe steps action
  docs/user_manual/ReadMe.md
Labels: documentation

#557 Add cooler node necessary parameters
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#560 Corrected error with add similar objects
  src/TechObject/ObjectsTree/S88Object.cs
  src/TechObject/TechObjectManager.cs
Labels: bugfix

#562 Fixed error when new project start
  src/FileSavers/SVGStatisticsSaver.cs
  src/ProjectManager.cs
Labels: bugfix

#554 Improve properties in editor
  src/Editor/ObjectProperty.cs
  src/TechObject/Base/BaseParameter.cs
  src/TechObject/ObjectsTree/UniversalObject/Action_Wash.cs
  src/TechObject/ObjectsTree/UniversalObject/Mode.cs
  src/TechObject/ObjectsTree/UniversalObject/Param.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#564 Fix error when close PAC setting without projects
  src/InterprojectExchange/Forms/InterprojectExchangeForm.cs
Labels: bugfix

#568 Update documentation about cooler node and cooling operation
  docs/user_manual/ReadMe.md
Labels: documentation

#566 Update version to 2020.10
  src/Properties/AssemblyInfo.cs
Labels: enhancement

#569 Add leavening operation parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: documentation, enhancement

#571 Add washing CIP parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#573 Fix error with loading files and libs when they don't exist
  src/ProjectManager.cs
Labels: bugfix

#575 Fix error with empty step name
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: bugfix

#574 New implementation for Equipment
  src/DFrm.cs
  src/Device/Device.cs
  src/EProjectManager.cs
  src/EasyEPlanner.csproj
  src/Editor/ObjectProperty.cs
  src/Lua/sys.lua
  src/Lua/sys_base_objects_description.lua
  src/StaticHelper/CommonConst.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/Properties/ActiveParameter.cs
  src/TechObject/Base/Properties/EquipmentParameter.cs
  src/TechObject/ObjectsTree/UniversalObject/Action.cs
  src/TechObject/ObjectsTree/UniversalObject/Action_AI_AO.cs
  src/TechObject/ObjectsTree/UniversalObject/Action_DI_DO.cs
  src/TechObject/ObjectsTree/UniversalObject/Action_Wash.cs
  src/TechObject/ObjectsTree/UniversalObject/Action_WashSeats.cs
  src/TechObject/ObjectsTree/UniversalObject/Equipment.cs
  src/TechObject/ObjectsTree/UniversalObject/Mode.cs
  src/TechObject/ObjectsTree/UniversalObject/ModesManager.cs
  src/TechObject/ObjectsTree/UniversalObject/Params.cs
  src/TechObject/ObjectsTree/UniversalObject/ParamsManager.cs
  src/TechObject/ObjectsTree/UniversalObject/State.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#582 Clear data when clicked on empty space in setUp PAC settings in InterProject Exchange
  src/InterprojectExchange/Forms/PACSettingsForm.cs
Labels: enhancement

#580 Update documentation about interproject exchange.
  docs/user_manual/InterprojectExchange.md
Labels: documentation

#584 Fix error with PAC settings edit mode changing
  src/InterprojectExchange/Forms/PACSettingsForm.cs
Labels: bugfix

#586 Alphabetical signals sort in interproject exchange
  src/InterprojectExchange/InterprojectExchangeSaver.cs
Labels: bugfix

#590 Fix restriction error
  src/TechObject/ObjectsTree/UniversalObject/Restriction.cs
Labels: bugfix

#588 Automatic run modbus server on controller
  src/FileSavers/ProjectDescriptionSaver.cs
  src/Lua/mainPattern.plua
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement

#595 Fix opening "Devices" and "Operations" window after reopen project
  src/Editor/NewEditorControl.cs
Labels: bugfix

#593 Fix error when statistics are saving
  src/FileSavers/SVGStatisticsSaver.cs
Labels: bugfix

#598 Show non editable global number in objects
  docs/user_manual/ReadMe.md
  docs/user_manual/images/TechObjectOperationNumbersParameter.jpg
  docs/user_manual/images/TechObjectOperationParameters.jpg
  docs/user_manual/images/TechObjectOperationSetUpNumbers.jpg
  docs/user_manual/images/TechObjectParameters.jpg
  docs/user_manual/images/exportObjectsForm.png
  docs/user_manual/images/higlight_dev.png
  docs/user_manual/images/loadImportedObjectsFormAfterImport.png
  docs/user_manual/images/operations_descr_in_eplan.png
  docs/user_manual/images/restrictions.png
  docs/user_manual/images/selected_restrictions.png
  docs/user_manual/images/set_base_oper.png
  docs/user_manual/images/techobject_descr.png
  docs/user_manual/images/work_with_fields_s88_ao.jpg
  src/Editor/NewEditorControl.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#600 Possibility to use Del button for delete
  docs/user_manual/images/NewEditor/attachObjects.jpg
  docs/user_manual/images/NewEditor/treeRootsExample.jpg
  docs/user_manual/images/NewEditor/unidentifiedDisabledObject.jpg
  docs/user_manual/images/NewEditor/unidentifiedObject.jpg
  docs/user_manual/images/NewEditor/unidentifiedObjectAfterInsert.jpg
  src/Editor/NewEditorControl.cs
  src/Editor/ObjectProperty.cs
  src/TechObject/ObjectsTree/UniversalObject/Equipment.cs
  src/TechObject/ObjectsTree/UniversalObject/ParamsManager.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#603 Fix equipment clear error
  src/TechObject/ObjectsTree/UniversalObject/Equipment.cs
Labels: bugfix

#601 Update work with base parameters in object
  docs/user_manual/ReadMe.md
  docs/user_manual/images/base_operation_props_set_up_parameters.png
  src/DFrm.cs
  src/EProjectManager.cs
  src/Editor/ITreeViewItem.cs
  src/Editor/NewEditorControl.cs
  src/Editor/ObjectProperty.cs
  src/Editor/TreeViewItem.cs
  src/Lua/sys_base_objects_description.lua
  src/Lua/sys_base_objects_initializer.lua
  src/Main/ShowDevicesAction.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseParameter.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/Properties/ActiveBoolParameter.cs
  src/TechObject/Base/Properties/ActiveParameter.cs
  src/TechObject/Base/Properties/EquipmentParameter.cs
  src/TechObject/Base/Properties/MainAggregateParameter.cs
  src/TechObject/ObjectsTree/UniversalObject/Action.cs
Labels: enhancement
