Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2020-03, with the labels that each got.

#162 Fixed synchronizing bug
  src/DeviceSynchronizer.cs
Labels: bugfix

#153 Improving base tank functionality
  docs/user_manual/ReadMe.md
  src/DBImitation/BaseOperationsDB.cs
  src/DBImitation/ObjectProperties.cs
  src/DBImitation/OperationsParams.cs
  src/DBImitation/TechObjectsEquipmentDB.cs
  src/EasyEPlanner.csproj
  src/PrgLuaSaver.cs
  src/ProjectManager.cs
  src/Properties/AssemblyInfo.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/TechObjects/BaseLine.cs
  src/TechObject/Base/TechObjects/BaseLineIn.cs
  src/TechObject/Base/TechObjects/BaseLineOut.cs
  src/TechObject/Base/TechObjects/BaseMixer.cs
  src/TechObject/Base/TechObjects/BaseTank.cs
  src/TechObject/Mode.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#164 Fixed displaying restrictions error
  src/ModeFrm.cs
Labels: bugfix

#168 Calculate tags count and refactoring
  src/EasyEPlanner.csproj
  src/ProjectManager.cs
  src/XMLReporter.cs
Labels: enhancement

#166 Corrected XML export
  docs/user_manual/ReadMe.md
  src/Device.cs
  src/XMLReporter.cs
Labels: documentation, enhancement

#169 Saving project statistics
  docs/user_manual/ReadMe.md
  src/DeviceBindingReader.cs
  src/DeviceReader.cs
  src/EProjectManager.cs
  src/EasyEPlanner.csproj
  src/FileSavers/Excel/ExcelDataCollector.cs
  src/FileSavers/Excel/ExcelRepoter.cs
  src/FileSavers/PrgLuaSaver.cs
  src/FileSavers/ProjectDescriptionSaver.cs
  src/FileSavers/SVGStatisticsSaver.cs
  src/FileSavers/XMLReporter.cs
  src/IOReader.cs
  src/Logs/LogFrm.Designer.cs
  src/Logs/LogFrm.cs
  src/Logs/LogFrm.resx
  src/Logs/Logs.cs
  src/ProjectConfiguration.cs
  src/ProjectManager.cs
  src/Properties/AssemblyInfo.cs
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/TechObject/TechObjectManager.cs
  src/main.cs
Labels: enhancement

#175 Proposes new logo
  docs/user_manual/images/EasyEplannerPreview.png
Labels: documentation, enhancement

#178 Added LT_IOLINK parameters for different tanks types
  docs/user_manual/ReadMe.md
  src/Device.cs
Labels: enhancement

#173 Fixed channels base export
  docs/user_manual/ReadMe.md
  docs/user_manual/images/channelBaseExportDialog.jpg
  src/EasyEPlanner.csproj
  src/FileSavers/XMLReporter.cs
  src/FileSavers/XMLReporterDialog.Designer.cs
  src/FileSavers/XMLReporterDialog.cs
  src/FileSavers/XMLReporterDialog.resx
  src/ProjectManager.cs
  src/TechObject/Step.cs
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
  src/main.cs
Labels: enhancement

#184 Added SB to Action Wash in DI
  src/TechObject/Action_Wash.cs
Labels: enhancement

#182 Added P_ERR for LT device
  docs/user_manual/ReadMe.md
  src/Device.cs
Labels: enhancement

#188 Modifying and moving main.plua to resources
  src/FileSavers/ProjectDescriptionSaver.cs
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement

#190 Updated doc about actions
  docs/user_manual/ReadMe.md
Labels: documentation

#195 Added posfix for Line in and Line out
  src/TechObject/Base/TechObjects/BaseLineIn.cs
  src/TechObject/Base/TechObjects/BaseLineOut.cs
Labels: bugfix

#194 Fixed ST parameter export for TE device
  docs/user_manual/ReadMe.md
  src/Device.cs
Labels: bugfix

#192 Added checking project IP addresses method
  docs/user_manual/ReadMe.md
  src/ConfigurationChecker.cs
  src/Device.cs
  src/IO.cs
  src/ProjectConfiguration.cs
  src/StaticHelper.cs
Labels: enhancement

#196 Implemented replacing equipment methods
  docs/user_manual/ReadMe.md
  src/DBImitation/TechObjectsEquipmentDB.cs
  src/Editor.cs
  src/Properties/AssemblyInfo.cs
  src/TechObject/Base/BaseProperty.cs
  src/TechObject/Base/Properties/ShowedProperty.cs
  src/TechObject/Equipment.cs
  src/TechObject/ModesManager.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#198 Added states functionality to steps (DI, DO, devices, etc.)
  src/Lua/sys.lua
  src/TechObject/Step.cs
Labels: enhancement

#203 Added require modules
  src/FileSavers/ProjectDescriptionSaver.cs
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement

#204 Added equipment to cooler node
  docs/user_manual/ReadMe.md
  src/DBImitation/TechObjectsEquipmentDB.cs
  src/TechObject/Base/TechObjects/BaseCooler.cs
Labels: enhancement

#205 Implemented cooling base operation
  src/TechObject/Base/TechObjects/BaseCooler.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
Labels: enhancement

#208 Added equipment to water tank
  docs/user_manual/ReadMe.md
  src/DBImitation/TechObjectsEquipmentDB.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
Labels: enhancement

#207 Missing fixes
  src/DBImitation/BaseOperationsDB.cs
  src/TechObject/Base/TechObjects/BaseCooler.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
Labels: enhancement

#210 Updated documentation about exporting XML devices parameters
  docs/user_manual/ReadMe.md
Labels: documentation

#213 Corrected automatic equipment binding
  src/TechObject/TechObject.cs
Labels: enhancement

#215 Separated saving base operations and their parameters
  src/TechObject/Base/TechObjects/BaseTank.cs
Labels: bugfix

#216 Added checking parameters
  docs/user_manual/ReadMe.md
  src/TechObject/Param.cs
  src/TechObject/Params.cs
  src/TechObject/ParamsManager.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#220 Corrected XML export for LS
  docs/user_manual/ReadMe.md
  src/Device.cs
Labels: enhancement

#222 Corrected LT IO-Link offset
  src/Device.cs
Labels: bugfix

#217 Added base object "Узел охлаждения ПИД"
  docs/user_manual/ReadMe.md
  src/DBImitation/BaseOperationsDB.cs
  src/DBImitation/Imitation.cs
  src/DBImitation/ObjectProperties.cs
  src/DBImitation/TechObjectsEquipmentDB.cs
  src/EasyEPlanner.csproj
  src/FileSavers/PrgLuaSaver.cs
  src/TechObject/Base/TechObjects/BaseCoolerPID.cs
Labels: enhancement

#218 Updated documentation about base functionality
  docs/user_manual/ReadMe.md
Labels: documentation

#224 Fixed mixproof offset
  src/Device.cs
Labels: bugfix

#226 Correct IO-Link TE parameters
  src/Device.cs
Labels: enhancement

#231 Added checking equals IP addresses in devices
  src/Device.cs
Labels: enhancement

#234 Correct AO export XML
  docs/user_manual/ReadMe.md
  src/Device.cs
Labels: enhancement

#179 Удалено сохранение устаревшего описания технологических объектов
  src/Lua/sys.lua
  src/TechObject/Mode.cs
Labels: enhancement

#239 Added pressure object to base objects
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseObjects.cs
  src/DataBaseImitation/BaseObjectsEquipment.cs
  src/DataBaseImitation/BaseOperations.cs
  src/EasyEPlanner.csproj
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/TechObject/Base/TechObjects/BasePressurePID.cs
Labels: enhancement

#240 Bind pressure node to attached objects
  src/FileSavers/PrgLuaSaver.cs
Labels: enhancement

#243 Corrected steps names
  src/DataBaseImitation/BaseOperationSteps.cs
  src/TechObject/Mode.cs
  src/TechObject/State.cs
  src/TechObject/Step.cs
Labels: enhancement

#238 New description "Узел охлаждения ПИД"
  src/DataBaseImitation/BaseObjectProperties.cs
  src/EasyEPlanner.csproj
  src/EditorCtrl.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/Properties/BoolShowedProperty.cs
  src/TechObject/Base/TechObjects/BaseCoolerPID.cs
Labels: enhancement

#247 Updated documentation about new steps names
  docs/user_manual/ReadMe.md
Labels: documentation

#248 Implemented ACTIVE_WORKING param into Water tank
  src/DataBaseImitation/BaseObjectProperties.cs
  src/DataBaseImitation/BaseOperations.cs
  src/DataBaseImitation/BaseOperationsParams.cs
  src/EditorCtrl.cs
  src/TechObject/Base/TechObjects/BaseWaterTank.cs
Labels: enhancement

#251 Added new flow node PID base object
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseObjects.cs
  src/DataBaseImitation/BaseObjectsEquipment.cs
  src/DataBaseImitation/BaseOperations.cs
  src/EasyEPlanner.csproj
  src/FileSavers/PrgLuaSaver.cs
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/TechObject/Base/TechObjects/BaseFlowNodePID.cs
Labels: enhancement

#252 Improved copy methods for modes
  src/TechObject/Action.cs
  src/TechObject/Action_AI_AO.cs
  src/TechObject/Action_DI_DO.cs
  src/TechObject/Action_Wash.cs
  src/TechObject/Action_WashSeats.cs
  src/TechObject/Mode.cs
  src/TechObject/ModesManager.cs
  src/TechObject/State.cs
  src/TechObject/Step.cs
Labels: enhancement

#250 Added heater node PID to base objects
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseObjects.cs
  src/DataBaseImitation/BaseObjectsEquipment.cs
  src/DataBaseImitation/BaseOperations.cs
  src/EasyEPlanner.csproj
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseProperty.cs
  src/TechObject/Base/Properties/BoolShowedProperty.cs
  src/TechObject/Base/TechObjects/BaseHeaterPID.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#254 Added wash POU
  docs/user_manual/ReadMe.md
  src/DataBaseImitation/BaseObjectProperties.cs
  src/DataBaseImitation/BaseOperations.cs
  src/TechObject/Base/TechObjects/BasePOU.cs
Labels: enhancement

#258 Fixed critical error and binding
  src/TechObject/Base/Properties/ShowedProperty.cs
  src/TechObject/Equipment.cs
Labels: bugfix

#256 Added T parameter in QT_IOLINK for export in XML
  docs/user_manual/ReadMe.md
  src/Device.cs
Labels: enhancement

#260 Custom handler for attached objects
  docs/user_manual/ReadMe.md
  src/TechObject/TechObject.cs
Labels: enhancement

#263 Returned Ctrl + X
  src/EditorCtrl.cs
Labels: bugfix
