Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2020-01, with the labels that each got.

#35 Added virtual LT and LS device subtypes
  src/Device.cs
Labels: enhancement

#29 Added button about add-in version
  docs/user_manual/ReadMe.md
  src/Properties/AssemblyInfo.cs
  src/main.cs
Labels: enhancement

#36 Update LS, LT documentation
  docs/user_manual/ReadMe.md
Labels: documentation

#40 Added GS device type to adding in turn on Signals
  docs/user_manual/ReadMe.md
  src/TechObject.cs
Labels: enhancement

#33 Added binding DI&DO to IO-Link
  docs/user_manual/ReadMe.md
  docs/user_manual/images/PXCIOLFuncText.png
  src/DFrm.cs
  src/Device.cs
  src/DeviceBindFromForm.cs
  src/EasyEPlanner.csproj
  src/IO.cs
  src/main.cs
Labels: enhancement

#43 Fixed saving empty channels
  src/Device.cs
Labels: bugfix

#44 Fixed cloning functions leading to wrong string in actions
  src/TechObject.cs
Labels: bugfix

#49 Fixed not existing channel
  src/Device.cs
Labels: bugfix

#46 Fixed binding algorithm for DI, DO channels to IO-Link
  docs/user_manual/ReadMe.md
  src/Device.cs
  src/DeviceBindFromForm.cs
  src/main.cs
Labels: enhancement

#47 Fixed export to excel
  src/ExcelRepoter.cs
  src/IO.cs
Labels: bugfix

#51 Fixed binding error
  src/DeviceBindFromForm.cs
  src/main.cs
Labels: bugfix

#57 Translated readme.md sections into english
  ReadMe.md
Labels: documentation

#56 Translated readme.md sections into English
  ReadMe.md
Labels: documentation

#60 Added PT DEV_SPAE device subtype
  docs/user_manual/ReadMe.md
  src/Device.cs
Labels: documentation, enhancement

#66 Добавлена информация о лицензии
  src/main.cs
Labels: enhancement

#53 Refactoring EplanIOManager and EplanDeviceManager classes
  src/ConfigurationChecker.cs
  src/Device.cs
  src/DeviceBindFromForm.cs
  src/DeviceBindingReader.cs
  src/DeviceReader.cs
  src/DeviceSynchronizer.cs
  src/EProjectManager.cs
  src/EasyEPlanner.csproj
  src/IO.cs
  src/IOReader.cs
  src/ProjectConfiguration.cs
  src/ProjectManager.cs
  src/StaticHelper.cs
  src/TechObject.cs
  src/main.cs
Labels: enhancement

#71 Добавлено количество клапанов
  docs/user_manual/ReadMe.md
Labels: documentation

#64 Добавлена возможность указания нескольких каталогов хранения описания проектов
  src/ProjectManager.cs
  src/main.cs
Labels: enhancement

#75 Removed automatic set P_ERR parameter in TE
  src/Device.cs
Labels: enhancement

#77 Корректное сохранение описания при отсутствии параметров
  src/TechObject.cs
Labels: bugfix

#78 Added checking empty articles in function
  src/Device.cs
Labels: enhancement

#79 Fixed base operation property
  src/TechObject.cs
Labels: bugfix

#85 Refactored TechObject.cs
  src/DBImitation/Imitation.cs
  src/EasyEPlanner.csproj
  src/EditorCtrl.cs
  src/TechObject.cs
  src/TechObject/Action.cs
  src/TechObject/Action_AI_AO.cs
  src/TechObject/Action_DI_DO.cs
  src/TechObject/Action_Wash.cs
  src/TechObject/Action_WashSeats.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseOperationProperty.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/LocalRestriction.cs
  src/TechObject/Mode.cs
  src/TechObject/ModesManager.cs
  src/TechObject/OperationParam.cs
  src/TechObject/OperationParams.cs
  src/TechObject/Param.cs
  src/TechObject/Params.cs
  src/TechObject/ParamsManager.cs
  src/TechObject/Restriction.cs
  src/TechObject/RestrictionManager.cs
  src/TechObject/State.cs
  src/TechObject/Step.cs
  src/TechObject/TechObject.cs
  src/TechObject/TechObjectManager.cs
  src/TechObject/TimersManager.cs
Labels: enhancement

#86 Fixed errors in prg.lua and update documentation
  docs/user_manual/ReadMe.md
  src/DBImitation/Imitation.cs
  src/ProjectManager.cs
  src/TechObject/TechObjectManager.cs
Labels: bugfix

#88 Added parameters for line
  src/DBImitation/Imitation.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#90 Fixed Lua syntax
  docs/user_manual/ReadMe.md
  src/TechObject/TechObjectManager.cs
Labels: bugfix, documentation

#91 Automatically adding channel
  src/Editor.cs
  src/TechObject/Base/BaseOperationProperty.cs
Labels: enhancement

#95 Fixed checking VC and M
  src/Device.cs
Labels: bugfix

#100 Внесены изменения в документации
  docs/user_manual/ReadMe.md
  docs/user_manual/images/set_vtug_tip.png
Labels: documentation

#98 Added small tank to base objects
  src/DBImitation/Imitation.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/TechObjectManager.cs
Labels: bugfix

#102 Fixed PT_IOLINK params
  src/Device.cs
Labels: bugfix

#109 Corrected adding float parameters to object
  src/TechObject/Params.cs
  src/TechObject/ParamsManager.cs
Labels: enhancement
