Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2020-06, with the labels that each got.

#381 Updated main.plua pattern
  src/EasyEPlanner.csproj
  src/FileSavers/ProjectDescriptionSaver.cs
  src/Lua/mainPattern.plua
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement, review

#387 Added not found default value
  src/TechObject/Base/Properties/ActiveParameter.cs
Labels: bugfix, review

#388 Added MEDIUM_CHANGE functional to base tank wash
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement, review

#389 Добавление базовых операций
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#390 Corrected out_pump description
  src/Lua/sys_base_objects_description.lua
Labels: bugfix

#395 Added equipment validation methods
  src/TechObject/Equipment.cs
Labels: enhancement, review

#396 Added tank lamp
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#399 Corrected out_pump documentation in Tank base object
  docs/user_manual/ReadMe.md
Labels: bugfix

#401 Added mix node operations
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#402 Corrected Excel to new pattern
  src/FileSavers/Excel/ExcelDataCollector.cs
  src/FileSavers/Excel/ExcelRepoter.cs
  src/IO/IOModule.cs
Labels: enhancement, review

#406 Checking M_ATV article
  docs/user_manual/ReadMe.md
  src/Device/IODevices/M.cs
Labels: enhancement

#403 Selecting mixing type in object
  docs/user_manual/ReadMe.md
  src/FileSavers/PrgLuaSaver.cs
  src/Lua/sys_base_objects_description.lua
  src/Lua/sys_base_objects_initializer.lua
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseParameter.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/Properties/ActiveParameter.cs
  src/TechObject/Equipment.cs
  src/TechObject/Mode.cs
  src/TechObject/Step.cs
  src/TechObject/TechObject.cs
Labels: enhancement, review

#408 Disabling unused parameters
  src/EasyEPlanner.csproj
  src/Editor/Editor.cs
  src/Editor/EditorCtrl.cs
  src/Editor/TechObjectsExporter.cs
  src/Editor/TechObjectsImporter.cs
  src/Lua/sys_base_objects_description.lua
  src/Lua/sys_base_objects_initializer.lua
  src/Properties/AssemblyInfo.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/Properties/ActiveBoolParameter.cs
  src/TechObject/Base/Properties/ActiveParameter.cs
  src/TechObject/Base/Properties/MainAggregateParameter.cs
  src/TechObject/Mode.cs
  src/TechObject/TechObject.cs
Labels: enhancement, review

#409 Added new IO-Link articles for devices
  src/Lua/sys_iolink_devices.lua
Labels: enhancement, review

#411 Updated prg.lua pattern for steam blast node
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement, review

#413 Fixed disabled parameter if default value is true
  src/TechObject/Base/Properties/MainAggregateParameter.cs
Labels: bugfix

#414 Automatic changing cross links in attached objects
  src/TechObject/TechObjectManager.cs
Labels: enhancement, review

#422 Corrected saving operation parameters in prg.lua
  src/TechObject/Base/BaseTechObject.cs
Labels: bugfix, review

#420 Corrected page with articles in Excel
  src/FileSavers/Excel/ExcelDataCollector.cs
Labels: enhancement, review

#423 Parameters names are changed for some agregates
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#424 Added using sterile node in prg.lua
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement, review

#426 Name changed for slow heating operation
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#427 Added cooling before leveaning operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#429 Checking value-sensitive parameters
  src/Logs/LogFrm.cs
  src/TechObject/Base/BaseTechObject.cs
Labels: enhancement, review

#430 Added constant tank level node (pump in)
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#431 Fixed some bugs in #428 and #430
  src/Lua/sys_base_objects_description.lua
  src/TechObject/Base/BaseTechObject.cs
Labels: bugfix

#433 Added in_tank_level_node module to prg.lua
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement

#328 Разработка теста по пользовательской документации
  docs/user_manual/test/readme.md
Labels: documentation

#392 Upgraded Add-In to 2.9 version
  ReadMe.md
  docs/user_manual/ReadMe.md
  src/EasyEPlanner.csproj
  src/Editor/EditorCtrl.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#436 Fixed error with Pause and Stop states
  src/Lua/sys.lua
  src/TechObject/Mode.cs
Labels: bugfix

#437 Improved pressure node
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#438 Improved pressure node
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#440 Not saving empty properties in Devices
  src/Device/IODevice.cs
Labels: enhancement

#441 PID-based and discrete tank level nodes
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#442 Fixed error with not found base object
  src/TechObject/TechObject.cs
Labels: bugfix

#445 Open tab from browser after press F1 in objects editor
  docs/user_manual/ReadMe.md
  src/Editor/Editor.cs
  src/Editor/EditorCtrl.cs
  src/ProjectManager.cs
  src/StaticHelper.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Equipment.cs
  src/TechObject/Mode.cs
  src/TechObject/ModesManager.cs
  src/TechObject/Params.cs
  src/TechObject/ParamsManager.cs
  src/TechObject/RestrictionManager.cs
  src/TechObject/State.cs
  src/TechObject/Step.cs
  src/TechObject/TechObject.cs
Labels: enhancement

#446 Fixed bug with useless .ini tag
  src/ProjectManager.cs
Labels: bugfix, enhancement

#447 Added parameters for cooling before leavening operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#448 Fixed bug with help system
  src/ProjectManager.cs
Labels: bugfix

#450 Added cooling after souring operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#452 Changed cooling before leavening operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#453 Added second hatch to tank
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement
