Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2021-02, with the labels that each got.

#742 Fix sterile air node name
  docs/user_manual/AutomaticInsertObjectFromEplanMacros.md
Labels: bugfix

#745 Fix bug when delete undefined object
  src/TechObject/TechObjectManager.cs
Labels: bugfix

#744 Add wash params to line with FILL or PUMPING operations
  src/TechObject/Base/BaseTechObject.cs
Labels: enhancement

#739 Possibility to add system parameters in objects
  EasyEplanner.Tests/EasyEplanner.Tests.csproj
  EasyEplanner.Tests/Editor.Test/ObjectProperty.Test.cs
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseTechObject.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/ParamOperationsProperty.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/ParamProperty.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/SystemParam.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/SystemParams.Test.cs
  docs/user_manual/ReadMe.md
  docs/user_manual/images/systemBaseParameters.png
  src/EasyEPlanner.csproj
  src/Editor/ObjectProperty.cs
  src/Lua/sys.lua
  src/Lua/sys_base_objects_description.lua
  src/Lua/sys_base_objects_initializer.lua
  src/Properties/AssemblyInfo.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/ObjectsTree/UniversalObject/Param.cs
  src/TechObject/ObjectsTree/UniversalObject/ParamOperationsProperty.cs
  src/TechObject/ObjectsTree/UniversalObject/ParamProperty.cs
  src/TechObject/ObjectsTree/UniversalObject/SystemParam.cs
  src/TechObject/ObjectsTree/UniversalObject/SystemParams.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#748 Add AUTO_DI param in tank's WORK operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#749 Delete useless project edit mode selector
  docs/user_manual/InterprojectExchange.md
  docs/user_manual/images/InterProjectExchange/PACSettings.png
  src/InterprojectExchange/Forms/FilterForm.Designer.cs
  src/InterprojectExchange/Forms/InterprojectExchangeForm.Designer.cs
  src/InterprojectExchange/Forms/InterprojectExchangeForm.cs
  src/InterprojectExchange/Forms/PACSettingsForm.Designer.cs
  src/InterprojectExchange/Forms/PACSettingsForm.cs
  src/InterprojectExchange/InterprojectExchange.cs
Labels: enhancement

#750 Correct clamp num in error messages
  src/Configuration/DeviceBindingReader.cs
Labels: enhancement

#746 Add system parameters for objects
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
  src/Lua/sys_base_objects_initializer.lua
Labels: enhancement

#753 Add automatic end of FILL operation parameter when last tank in queue is empty
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#756 Correct PID parameters
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: bugfix

#757 Fix error with restrictions if unselecting operation
  src/TechObject/ObjectsTree/UniversalObject/LocalRestriction.cs
  src/TechObject/ObjectsTree/UniversalObject/Restriction.cs
Labels: bugfix

#751 Rename devices during synchronizing in base operation additional properties
  EasyEplanner.Tests/Configuration.Test/DeviceSynchronizeService.Test.cs
  EasyEplanner.Tests/EasyEplanner.Tests.csproj
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseParameter.Test.cs
  src/Configuration/DeviceSynchronizeService.cs
  src/Configuration/DeviceSynchronizer.cs
  src/Device/Device.cs
  src/Device/DeviceManager.cs
  src/EasyEPlanner.csproj
  src/Editor/DrawInfo.cs
  src/Editor/ObjectProperty.cs
  src/FileSavers/PrgLuaSaver.cs
  src/TechObject/Base/BaseOperation.cs
  src/TechObject/Base/BaseParameter.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/Properties/EquipmentParameter.cs
  src/TechObject/ObjectsTree/UniversalObject/Action.cs
  src/TechObject/ObjectsTree/UniversalObject/Mode.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement

#760 Add whey separation turnover to tank
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#761 Correct devices subtypes description in documentation
  docs/user_manual/ReadMe.md
Labels: bugfix, documentation

#762 BaseParameter shouldn't display "Нет" if default value equals value
  src/TechObject/Base/BaseParameter.cs
Labels: bugfix

#758 Reset base tech object through editor
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/SystemParams.Test.cs
  docs/user_manual/ReadMe.md
  docs/user_manual/images/techobject_descr.png
  src/EasyEPlanner.csproj
  src/Editor/IBaseObjChangeable.cs
  src/Editor/ImportExport/TechObjectsImporter.cs
  src/Editor/NewEditorControl.Designer.cs
  src/Editor/NewEditorControl.cs
  src/Editor/NewEditorControl.resx
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/Resources/changeObj.png
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/ITechObjectManager.cs
  src/TechObject/ObjectsTree/BaseObject.cs
  src/TechObject/ObjectsTree/ProcessCell.cs
  src/TechObject/ObjectsTree/S88Object.cs
  src/TechObject/ObjectsTree/Unidentified.cs
  src/TechObject/ObjectsTree/UniversalObject/Equipment.cs
  src/TechObject/ObjectsTree/UniversalObject/SystemParams.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
  src/TechObject/ObjectsTree/UserObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement, work in progress

#764 Sort S88 objects in tree
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#765 Correct reset base tech object documentation
  docs/user_manual/ReadMe.md
Labels: bugfix

#769 Update process cell number 10 parameter
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#767 Automatic insert parameters when inserting new object
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseParameter.Test.cs
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseTechObject.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Param.Test.cs
  src/Lua/sys_base_objects_description.lua
  src/Lua/sys_base_objects_initializer.lua
  src/Properties/Resources.resx
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/ObjectsTree/UniversalObject/Param.cs
  src/TechObject/ObjectsTree/UniversalObject/ParamsManager.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#772 Add new params to whey separation turnover
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#771 Fix mixing by revolutions
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: bugfix

#773 Add errors message if AI->AO group or DI->DO group were filled wrong
  src/TechObject/ObjectsTree/UniversalObject/Action.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement

#775 Add VC to action wash
  docs/user_manual/ReadMe.md
  src/TechObject/ObjectsTree/UniversalObject/ActionWash.cs
Labels: bugfix

#778 Fix DI->DO and AI->AO group names
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: bugfix

#777 Add WHEY_PUMDOWN operation with steps and properties
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#783 Doesn't copy first step when you are trying to replace it
  src/TechObject/ObjectsTree/UniversalObject/State.cs
Labels: bugfix

#785 Add MAX_TIME parameter to whey separation turnover operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement
