Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2021-06, with the labels that each got.

#842 Added auto di parameter for work
  docs/user_manual/ReadMe.md
Labels: documentation

#844 Move documentation about base objects to another source
  docs/user_manual/ReadMe.md
Labels: documentation

#846 Correct getting device from EplanName for PID errors
  src/Device/DeviceManager.cs
  src/Properties/AssemblyInfo.cs
Labels: bugfix

#848 Replace EplanName generating and correct result of GetDevice method
  EasyEplanner.Tests/Device.Test/Device.Test.cs
  EasyEplanner.Tests/Device.Test/DeviceManager.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/AI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/AO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/C.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/F.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FQT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/GS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HA.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HL.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/M.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/PT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/QT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/SB.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/TE.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/V.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/VC.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/WT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/Y(DEV_VTUG).Test.cs
  src/Device/Device.cs
  src/Device/DeviceManager.cs
  src/Device/IODevice.cs
  src/Device/IODevices/AI.cs
  src/Device/IODevices/AO.cs
  src/Device/IODevices/C.cs
  src/Device/IODevices/DI.cs
  src/Device/IODevices/DO.cs
  src/Device/IODevices/F.cs
  src/Device/IODevices/FQT.cs
  src/Device/IODevices/FS.cs
  src/Device/IODevices/GS.cs
  src/Device/IODevices/HA.cs
  src/Device/IODevices/HL.cs
  src/Device/IODevices/LS.cs
  src/Device/IODevices/LT.cs
  src/Device/IODevices/M.cs
  src/Device/IODevices/PT.cs
  src/Device/IODevices/QT.cs
  src/Device/IODevices/SB.cs
  src/Device/IODevices/TE.cs
  src/Device/IODevices/V.cs
  src/Device/IODevices/VC.cs
  src/Device/IODevices/WT.cs
  src/Device/IODevices/Y(DEV_VTUG).cs
  src/DeviceBindFromForm.cs
  src/EProjectManager/SelectInteractionWhileEditModes.cs
  src/FileSavers/Excel/ExcelDataCollector.cs
  src/IO/IOModule.cs
  src/ModulesBindingUpdater.cs
Labels: enhancement

#850 Check incorrect long values in IPConverter
  src/StaticHelper/IPConverter.cs
Labels: bugfix

#854 Remove P_DT tag from HL device
  EasyEplanner.Tests/Device.Test/IODevice.Test/HL.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/IODevices/HL.cs
Labels: enhancement

#857 Fix generating arrays in channel base
  src/Device/IODevice.cs
  src/TechObject/TechObjectXMLMaker.cs
Labels: bugfix

#856 add GS as DI in DI->DO groups and HL as DO
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Action.Test.cs
  docs/user_manual/ReadMe.md
  src/TechObject/ObjectsTree/UniversalObject/Action.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement

#825 Add light column device (HLA)
  EasyEplanner.Tests/Device.Test/IODevice.Test/HLA.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/DeviceManager.cs
  src/Device/DeviceSubTypeEnum.cs
  src/Device/DeviceTypeEnum.cs
  src/Device/IODevice.cs
  src/Device/IODevices/HLA.cs
  src/EasyEPlanner.csproj
  src/Lua/sys_devices_mock_generator.lua
Labels: enhancement
