Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2021-07, with the labels that each got.

#861 Add light column device (HLA) properties
  EasyEplanner.Tests/Device.Test/IODevice.Test/HLA.Test.cs
  src/Device/IODevices/HLA.cs
Labels: enhancement

#862 Update LS device description
  EasyEplanner.Tests/Device.Test/IODevice.Test/LS.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/IODevices/LS.cs
Labels: enhancement

#863 Add HLA control module description
  docs/user_manual/ReadMe.md
Labels: documentation

#864 Return deleted unit-tests for HLA
  EasyEplanner.Tests/Device.Test/IODevice.Test/HLA.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/IODevice.cs
  src/Properties/AssemblyInfo.cs
Labels: bugfix

#866 Correct order in attached objects, groups, etc. for every object
  src/TechObject/ObjectsTree/UniversalObject/AttachedObjects.cs
Labels: bugfix

#868 Add virtual subtypes for all remaining devices
  EasyEplanner.Tests/Device.Test/Device.Test.cs
  EasyEplanner.Tests/Device.Test/DeviceManager.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/AI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/AO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/C.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/F.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FQT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/GS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HA.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HL.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/HLA.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/M.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/PT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/QT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/SB.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/TE.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/V.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/VC.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/WT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/Y(DEV_VTUG).Test.cs
  docs/user_manual/ReadMe.md
  src/Device/DeviceSubTypeEnum.cs
  src/Device/IODevice.cs
  src/Device/IODevices/AI.cs
  src/Device/IODevices/AO.cs
  src/Device/IODevices/C.cs
  src/Device/IODevices/DI.cs
  src/Device/IODevices/DO.cs
  src/Device/IODevices/F.cs
  src/Device/IODevices/FQT.cs
  src/Device/IODevices/FS.cs
  src/Device/IODevices/GS.cs
  src/Device/IODevices/HA.cs
  src/Device/IODevices/HL.cs
  src/Device/IODevices/HLA.cs
  src/Device/IODevices/LS.cs
  src/Device/IODevices/LT.cs
  src/Device/IODevices/M.cs
  src/Device/IODevices/PT.cs
  src/Device/IODevices/QT.cs
  src/Device/IODevices/SB.cs
  src/Device/IODevices/TE.cs
  src/Device/IODevices/V.cs
  src/Device/IODevices/VC.cs
  src/Device/IODevices/WT.cs
  src/Device/IODevices/Y(DEV_VTUG).cs
  src/Device/Parameter.cs
  src/Device/Property.cs
  src/Device/RuntimeParameter.cs
  src/Device/Tag.cs
  src/EasyEPlanner.csproj
  src/TechObject/ObjectsTree/UniversalObject/ActionWash.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement

#869 Add info about object naming in Eplan
  docs/user_manual/ReadMe.md
Labels: documentation

#870 Parameters for finding linear of motor shaft speed in M_ATV
  EasyEplanner.Tests/Device.Test/IODevice.Test/M.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/IODevices/M.cs
  src/Device/Parameter.cs
Labels: enhancement

#871 Add checked devices action
  docs/user_manual/ReadMe.md
  src/Lua/sys.lua
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement

#874 Add CAM device
  EasyEplanner.Tests/Device.Test/IODevice.Test/CAM.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/DeviceManager.cs
  src/Device/DeviceSubTypeEnum.cs
  src/Device/DeviceTypeEnum.cs
  src/Device/IODevice.cs
  src/Device/IODevices/CAM.cs
  src/Device/Parameter.cs
  src/Device/Tag.cs
  src/EasyEPlanner.csproj
Labels: enhancement

#875 Add CAM to interproject exchange
  src/Lua/sys_devices_mock_generator.lua
Labels: bugfix

#878 Move linear speed from M_ATV subtype to M_ATV_LINEAR
  EasyEplanner.Tests/Device.Test/IODevice.Test/M.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/DeviceSubTypeEnum.cs
  src/Device/IODevices/M.cs
  src/Device/Tag.cs
  src/TechObject/ObjectsTree/UniversalObject/ActionWash.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement

#879 Refactoring parameters and tags, fix CAM
  EasyEplanner.Tests/Device.Test/IODevice.Test/AI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/AO.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/CAM.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/DI.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FQT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/FS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/GS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LS.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/LT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/M.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/PT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/QT.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/SB.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/V.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/WT.Test.cs
  src/Device/IODevices/AI.cs
  src/Device/IODevices/AO.cs
  src/Device/IODevices/CAM.cs
  src/Device/IODevices/DI.cs
  src/Device/IODevices/FQT.cs
  src/Device/IODevices/FS.cs
  src/Device/IODevices/GS.cs
  src/Device/IODevices/LS.cs
  src/Device/IODevices/LT.cs
  src/Device/IODevices/M.cs
  src/Device/IODevices/PT.cs
  src/Device/IODevices/QT.cs
  src/Device/IODevices/SB.cs
  src/Device/IODevices/V.cs
  src/Device/IODevices/WT.cs
  src/Device/Parameter.cs
  src/Device/Tag.cs
Labels: enhancement
