Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2021-08, with the labels that each got.

#881 [fix] Change channels order
  src/Device/IODevices/CAM.cs
Labels: enhancement

#884 Update documentation for CAM device
  docs/user_manual/ReadMe.md
Labels: documentation, enhancement

#886 Fix Excel export because of new Actions
  src/FileSavers/Excel/ExcelDataCollector.cs
Labels: bugfix

#885 Fix highlighting devices in Action
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Step.Test.cs
  src/Properties/AssemblyInfo.cs
  src/TechObject/ObjectsTree/UniversalObject/ActionGroup.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: bugfix

#888 Add GS and DI devices using in "To step by condition" action
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/ActionToStepByCondition.Tests.cs
  docs/user_manual/ReadMe.md
  src/TechObject/ObjectsTree/UniversalObject/Action.cs
  src/TechObject/ObjectsTree/UniversalObject/ActionToStepByCondition.cs
Labels: enhancement

#887 Correct behavior in InterProjectExchange if user ignored errors during loading data
  src/InterprojectExchange/InterprojectExchangeSaver.cs
  src/InterprojectExchange/InterprojectExchangeStarter.cs
Labels: bugfix

#889 Fix adding parameters to operations if replacing from "Parameters" link
  src/TechObject/ObjectsTree/UniversalObject/ParamsManager.cs
Labels: bugfix

#890 Correct loading of checked devices
  src/Lua/sys.lua
Labels: bugfix

#891 Refactoring Actions code
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Action.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/ActionToStepByCondition.Tests.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/ActionWash.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/GroupableAction.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Step.Test.cs
  src/EasyEPlanner.csproj
  src/Editor/ITreeViewItem.cs
  src/Editor/NewEditorControl.cs
  src/Editor/ObjectProperty.cs
  src/Editor/TreeViewItem.cs
  src/FileSavers/Excel/ExcelDataCollector.cs
  src/Lua/sys.lua
  src/TechObject/ObjectsTree/UniversalObject/ActionGroup.cs
  src/TechObject/ObjectsTree/UniversalObject/ActionToStepByCondition.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/Action.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionGroup.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionGroupWash.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionToStepByCondition.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionWash.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/GroupableAction.cs
  src/TechObject/ObjectsTree/UniversalObject/State.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement

#892 Add documentation about possibility to have more than one folder for projects
  docs/user_manual/ReadMe.md
Labels: documentation

#896 Update bind because of new info from EPLAN
  src/Configuration/DeviceBindingReader.cs
  src/StaticHelper/DeviceBindingHelper.cs
Labels: bugfix

#897 Delete version control folders if they were added to shadow assembly
  src/ProjectManager.cs
Labels: bugfix
