Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2021-12, with the labels that each got.

#953 Hide deprecated objects with possibility to use them in old projects
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseTechObject.Test.cs
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseTechObjectManager.Test.cs
  docs/user_manual/ReadMe.md
  src/Editor/ObjectAdder/ObjectAdder.cs
  src/Lua/sys_base_objects_initializer.lua
  src/Properties/AssemblyInfo.cs
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/BaseTechObjectLoader.cs
  src/TechObject/Base/BaseTechObjectManager.cs
Labels: enhancement, safe to test

#951 Multiple binding aggregates to aggregates
  docs/user_manual/ReadMe.md
  src/FileSavers/PrgLuaSaver.cs
  src/ModeFrm.cs
  src/TechObject/ITechObjectManager.cs
  src/TechObject/ObjectsTree/BaseObject.cs
  src/TechObject/ObjectsTree/UniversalObject/AttachedObjects.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement, safe to test

#954 Add link to developer manual
  ReadMe.md
Labels: documentation

#961 Return generating main.devices.lua with new structure
  docs/user_manual/ReadMe.md
  src/Device/DeviceManager.cs
  src/FileSavers/ProjectDescriptionSaver.cs
Labels: bugfix

#960 Don't check disabled properties if UI haven't opened yet
  src/TechObject/Base/BaseOperation.cs
Labels: bugfix

#963 Possibility to replace actions in objects
  src/TechObject/ObjectsTree/UniversalObject/Actions/Action.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement, safe to test

#962 Possibility to add float runtime parameters
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseTechObject.Test.cs
  src/Lua/sys_base_objects_initializer.lua
  src/Properties/Resources.resx
  src/TechObject/Base/BaseParameter.cs
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/Properties/EquipmentParameter.cs
  src/TechObject/ObjectsTree/UniversalObject/ParamsManager.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement, safe to test

#965 Back main.devices template
  src/Device/DeviceManager.cs
Labels: bug, bugfix

#964 Add DO devices to upper and lower seats actions
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Step.Test.cs
  docs/user_manual/ReadMe.md
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement, safe to test

#966 Add file versions to main.*.lua files
  src/AssemblyVersion.cs
  src/EasyEPlanner.csproj
  src/FileSavers/ProjectDescriptionSaver.cs
  src/InterprojectExchange/InterprojectExchangeSaver.cs
  src/Lua/mainPattern.plua
  src/Main/AboutProgrammAction.cs
  src/Properties/Resources.Designer.cs
  src/Properties/Resources.resx
Labels: enhancement

#967 Block station number if no signals
  docs/user_manual/InterprojectExchange.md
  src/InterprojectExchange/Forms/PACSettingsForm.cs
  src/Properties/AssemblyInfo.cs
Labels: enhancement
