Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2021-04, with the labels that each got.

#801 Automatic set up Monitor name after inserting new object
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseTechObjectManager.Test.cs
  src/Lua/sys_base_objects_initializer.lua
  src/Properties/Resources.resx
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/Base/BaseTechObjectLoader.cs
  src/TechObject/Base/BaseTechObjectManager.cs
  src/TechObject/ObjectsTree/BaseObject.cs
  src/TechObject/ObjectsTree/UniversalObject/AttachedObjects.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#802 Update version to 2021.4
  src/Properties/AssemblyInfo.cs
Labels: enhancement

#804 New interproject exchange saving data algorithm
  docs/user_manual/InterprojectExchange.md
  src/InterprojectExchange/Forms/InterprojectExchangeForm.Designer.cs
  src/InterprojectExchange/InterprojectExchangeSaver.cs
Labels: enhancement

#806 Correct using testing project script
  src/CMD/TestProjectScript.txt
  src/Configuration/ProjectHealthChecker.cs
  src/ProjectManager.cs
Labels: enhancement

#808 Correct running testing script
  src/CMD/TestProjectScript.txt
  src/Configuration/ProjectHealthChecker.cs
Labels: enhancement

#811 Add PID-regulator as Control Module
  EasyEplanner.Tests/Device.Test/IODevice.Test.cs
  EasyEplanner.Tests/Device.Test/IODevice.Test/R.Test.cs
  EasyEplanner.Tests/EasyEplanner.Tests.csproj
  EasyEplanner.Tests/IO.Test/IOModuleInfo.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Action.Test.cs
  docs/user_manual/ReadMe.md
  docs/user_manual/images/MakeCascadePID.jpg
  docs/user_manual/images/OverridePIDProperties.jpg
  docs/user_manual/images/RunPID.jpg
  src/Device/DeviceManager.cs
  src/Device/DeviceTypeEnum.cs
  src/Device/IODevice.cs
  src/Device/IODevices/R.cs
  src/EasyEPlanner.csproj
  src/FileSavers/XMLReporter.cs
  src/TechObject/ObjectsTree/UniversalObject/ActionWash.cs
Labels: enhancement

#813 Rename R dev to C dev
  EasyEplanner.Tests/Device.Test/IODevice.Test/C.Test.cs
  docs/user_manual/ReadMe.md
  docs/user_manual/images/MakeCascadePID.jpg
  docs/user_manual/images/MakeCascadePID.png
  docs/user_manual/images/RunPID.png
  src/Device/DeviceManager.cs
  src/Device/DeviceTypeEnum.cs
  src/Device/IODevices/C.cs
  src/EasyEPlanner.csproj
  src/FileSavers/XMLReporter.cs
  src/TechObject/ObjectsTree/UniversalObject/ActionWash.cs
Labels: bugfix

#814 [doc] Remove outdated description
  docs/user_manual/ReadMe.md
  docs/user_manual/images/operations_descr.png
Labels: bugfix, documentation

#816 Automatic define C device through other device names
  EasyEplanner.Tests/Device.Test/DeviceManager.Test.cs
  docs/user_manual/ReadMe.md
  docs/user_manual/images/MakeCascadePID.png
  docs/user_manual/images/RunPID.jpg
  docs/user_manual/images/RunPID.png
  src/Device/DeviceManager.cs
  src/EProjectManager/SelectInteractionWhileEditModes.cs
Labels: bugfix

#817 Fix documentation about PID regulator
  docs/user_manual/ReadMe.md
Labels: bugfix, documentation
