Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2021-01, with the labels that each got.

#697 Update revision version to the newest
  src/Properties/AssemblyInfo.cs
Labels: enhancement

#703 Remove deleting file if model empty
  src/InterprojectExchange/InterprojectExchangeSaver.cs
Labels: bugfix

#701 Add heating operation to Tank
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#699 Add Fill2 operation to Tank object
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#705 Unbind parameter before replace
  src/TechObject/ObjectsTree/UniversalObject/Params.cs
Labels: bugfix

#706 Add additional parameter to heating operation in tank object
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#708 Possibility to attach objects with equal obj type
  src/Lua/sys.lua
  src/Lua/sys_base_objects_description.lua
  src/Lua/sys_base_objects_initializer.lua
  src/TechObject/Base/BaseTechObject.cs
  src/TechObject/ObjectsTree/BaseObject.cs
  src/TechObject/ObjectsTree/UniversalObject/AttachedObjects.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#710 Add cip_node object
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
  src/Properties/Resources.resx
Labels: enhancement

#711 Update SVG in documentation
  docs/user_manual/ReadMe.md
  docs/user_manual/UML/base_objects_s88.uxf
  docs/user_manual/UML/control_modules_s88.uxf
  docs/user_manual/images/control_modules_s88.svg
  docs/user_manual/images/s88_objects.svg
Labels: documentation

#714 Insert object after insert object macros
  docs/user_manual/AutomaticInsertObjectFromEplanMacros.md
  docs/user_manual/ReadMe.md
  docs/user_manual/images/InsertObjectFromMacro/afterInsertingMacros.png
  docs/user_manual/images/InsertObjectFromMacro/createMacros.png
  docs/user_manual/images/InsertObjectFromMacro/createMacrosMenu.png
  docs/user_manual/images/InsertObjectFromMacro/insertMacrosMenu.png
  docs/user_manual/images/InsertObjectFromMacro/objectNameInFunctionalText.png
  docs/user_manual/images/InsertObjectFromMacro/prepareSymbolForMacros.png
  docs/user_manual/images/InsertObjectFromMacro/symbolFunction.png
  docs/user_manual/images/InsertObjectFromMacro/symbolPreview.png
  docs/user_manual/images/InsertObjectFromMacro/symbolProperty.png
  docs/user_manual/images/InsertObjectFromMacro/symbolPropertyMenu.png
  docs/user_manual/images/InsertObjectFromMacro/symbolsLibMenu.png
  docs/user_manual/images/InsertObjectFromMacro/symbolsLibSetUp.png
  docs/user_manual/images/InsertObjectFromMacro/symbolsMenu.png
  src/EProjectManager.cs
  src/EProjectManager/EProjectManager.cs
  src/EProjectManager/EplanEventListener.cs
  src/EProjectManager/InsertMacrosInteraction.cs
  src/EProjectManager/SelectInteractionWhileEditModes.cs
  src/EasyEPlanner.csproj
  src/Editor/Editor.cs
  src/Editor/IEditor.cs
  src/Editor/NewEditorControl.cs
  src/ProjectManager.cs
  src/TechObject/ITechObjectManager.cs
  src/TechObject/ObjectsTree/BaseObject.cs
  src/TechObject/ObjectsTree/ProcessCell.cs
  src/TechObject/ObjectsTree/S88Object.cs
  src/TechObject/ObjectsTree/UniversalObject/ActionGroup.cs
  src/TechObject/ObjectsTree/UniversalObject/ActionGroupWash.cs
  src/TechObject/ObjectsTree/UniversalObject/Equipment.cs
  src/TechObject/ObjectsTree/UniversalObject/Mode.cs
  src/TechObject/ObjectsTree/UniversalObject/ModesManager.cs
  src/TechObject/ObjectsTree/UniversalObject/Params.cs
  src/TechObject/ObjectsTree/UniversalObject/ParamsManager.cs
  src/TechObject/ObjectsTree/UniversalObject/RestrictionManager.cs
  src/TechObject/ObjectsTree/UniversalObject/State.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
  src/TechObject/ObjectsTree/UserObject.cs
  src/TechObject/TechObjectManager.cs
Labels: enhancement

#715 Fix parameter name for operation "LEAVENING"
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: bugfix

#719 Add WORK operation to Pasteurizator object
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#721 Add russian and german readme
  ReadMe.md
  docs/de/readme.md
  docs/ru/readme.md
Labels: documentation, enhancement

#725 Add new operations and parameters to cooler and heating nodes
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement

#731 Add restriction for TechObject name in 50 symbols
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#732 Add number symbol to DisplayText in TechObject
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#733 Delete useless space symbol in Equipment section in main.objects
  src/TechObject/ObjectsTree/UniversalObject/Equipment.cs
Labels: bugfix

#735 Implement correcting attach objects
  src/TechObject/ITechObjectManager.cs
  src/TechObject/ObjectsTree/BaseObject.cs
  src/TechObject/ObjectsTree/ProcessCell.cs
  src/TechObject/ObjectsTree/Unidentified.cs
  src/TechObject/ObjectsTree/UserObject.cs
  src/TechObject/TechObjectManager.cs
Labels: bugfix

#737 Add line volume param to fill operation
  docs/user_manual/ReadMe.md
  src/Lua/sys_base_objects_description.lua
Labels: enhancement
