Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2021-11, with the labels that each got.

#931 Update links route in Deutschland and Russian documentation
  docs/de/readme.md
  docs/ru/readme.md
Labels: bugfix

#932 Correct user doc link in russian doc
  docs/ru/readme.md
Labels: bugfix

#934 Developer manual
  docs/developer_manual/ReadMe.md
  docs/developer_manual/images/base-objects-folder.PNG
  docs/developer_manual/images/cmd-folder.PNG
  docs/developer_manual/images/eplanner-folder.PNG
  docs/developer_manual/images/eplanner-root-project.PNG
  docs/developer_manual/images/idle-time-module-project.PNG
  docs/developer_manual/images/lua-folder.PNG
  docs/developer_manual/images/sign-add-in-first-step.PNG
  docs/developer_manual/images/sign-add-in-second-step.PNG
  docs/user_manual/ReadMe.md
Labels: documentation

#937 Fix images
  docs/developer_manual/ReadMe.md
Labels: bugfix

#938 Update git workflow
  .github/workflows/msbuild.yml
Labels: bugfix

#936 User error if project files are bad after renaming (Nemenkov case)
  src/InterprojectExchange/Forms/InterprojectExchangeForm.cs
  src/InterprojectExchange/InterprojectExchange.cs
  src/InterprojectExchange/InterprojectExchangeStarter.cs
Labels: bugfix, safe to test

#939 Use local test script if it presents
  src/CMD/TestProjectScript.txt
Labels: documentation, enhancement

#943 Return generating main.devices.lua
  docs/user_manual/ReadMe.md
  src/Device/DeviceManager.cs
  src/FileSavers/ProjectDescriptionSaver.cs
Labels: enhancement

#946 Deleted main.objects.lua or/and main.restrictions.lua exception
  src/ProjectManager.cs
Labels: bugfix

#948 Add SYSTEM.VERSION string tag
  src/FileSavers/XMLReporter.cs
  src/TechObject/TechObjectXMLMaker.cs
Labels: enhancement, safe to test

#949 Update script for run project testing
  src/CMD/TestProjectScript.txt
Labels: enhancement
