Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2022-04, with the labels that each got.

#999 Add IO-Link IFM SM6100
  docs/user_manual/ReadMe.md
  src/Device/DeviceSubTypeEnum.cs
  src/Device/IODevices/FQT.cs
  src/Lua/sys_iolink_devices.lua
Labels: enhancement

#1003 Update version to April 2022
  src/Properties/AssemblyInfo.cs
Labels: documentation

#1004 Add to manual FQT_IOLINK
  docs/user_manual/ReadMe.md
Labels: documentation

#1005 Fix build GitHub action
  .github/workflows/msbuild.yml
Labels: bugfix

#995 Add groups to ActionToStepByCondition
  EasyEplanner.Tests/Editor.Test/ObjectProperty.Test.cs
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseTechObject.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/ActionToStepByCondition.Tests.cs
  docs/user_manual/ReadMe.md
  src/FileSavers/Excel/ExcelDataCollector.cs
  src/FileSavers/Excel/ExcelRepoter.cs
  src/Lua/sys.lua
  src/TechObject/ObjectsTree/UniversalObject/Actions/Action.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionGroup.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionGroupWash.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionToStepByCondition.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionWash.cs
  src/TechObject/ObjectsTree/UniversalObject/State.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement, safe to test
