Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2023-02, with the labels that each got.

#1113 [github actions] Remove extra files from build results
  .github/workflows/msbuild.yml
Labels: safe to test

#1115 [GitHub actions] Fix test result
  .github/workflows/msbuild.yml
Labels: safe to test

#1116 Fix save files with full disk
  src/FileSavers/ProjectDescriptionSaver.cs
Labels: bugfix, safe to test

#1119 [doc] Edited mistakes in user_manual
  docs/user_manual/ReadMe.md
Labels: documentation

#1118 Power clamp binding prohibition
  docs/user_manual/ReadMe.md
  src/Configuration/DeviceBindingReader.cs
  src/DeviceBindFromForm.cs
Labels: safe to test

#1120 Update version to February 2023
  EasyEplanner.Tests/EasyEplanner.Tests.csproj
  src/Properties/AssemblyInfo.cs
Labels: documentation, safe to test

#1117 Add packages to "main.plua" pattern
  EasyEplanner.Tests/FileSaver.Test/ProjectDescriptionSaver.Test.cs
  EasyEplanner.Tests/IO.Test/IONode.Test.cs
  EasyEplanner.Tests/TechObject.Test/Base.Test/BaseTechObjectLoader.Test.cs
  docs/user_manual/ReadMe.md
  src/FileSavers/ProjectDescriptionSaver.cs
  src/Lua/mainPattern.plua
  src/Lua/sys_base_objects_initializer.lua
  src/TechObject/Base/BaseTechObjectLoader.cs
Labels: safe to test
