Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2023-01, with the labels that each got.

#1100 исправление пунктуационной ошибки
  ReadMe.md
Labels: documentation

#1105 Add new valve subtype
  EasyEplanner.Tests/EplanDevice.Test/IODevice.Test/V.Test.cs
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/ActionWash.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/DeviceSubTypeEnum.cs
  src/Device/IODevices/V.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionWash.cs
Labels: enhancement, safe to test

#1106 [fix] Correct processing "V_MINI_FLUSHING" valve subtype
  src/Device/IODevices/V.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: bugfix, safe to test

#1110 Update version to January 2023
  src/Properties/AssemblyInfo.cs
Labels: documentation
