Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2023-05, with the labels that each got.

#1159 Fix save next_step_n
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: bugfix

#1149 Add IP range list to project propeties
  EasyEplanner.Tests/Configuration.Test/CommonConstPatterns.Test.cs
  EasyEplanner.Tests/StaticHelper.Test/IPConverter.Test.cs
  docs/user_manual/ReadMe.md
  src/Configuration/ConfigurationChecker.cs
  src/Configuration/ProjectConfiguration.cs
  src/Device/DeviceManager.cs
  src/StaticHelper/CommonConst.cs
  src/StaticHelper/IPConverter.cs
Labels: enhancement

#1162 Add allowed device "SB" to action "to step if"
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Step.Test.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement

#1164 Add ability to copy and paste "AttachedObjects"
  src/Editor/ObjectProperty.cs
  src/TechObject/ObjectsTree/BaseObject.cs
  src/TechObject/ObjectsTree/UniversalObject/AttachedObjects.cs
  src/TechObject/ObjectsTree/UniversalObject/TechObject.cs
Labels: enhancement

#1168 Доработано описание действий в руководстве пользователя
  docs/user_manual/ReadMe.md
Labels: documentation, enhancement

#1167 Add attached_object to step
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Step.Test.cs
  src/Lua/sys.lua
  src/ModeFrm.cs
  src/TechObject/ObjectsTree/UniversalObject/AttachedObjects.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement
