Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2024-02, with the labels that each got.

#1316 [manual] Update control_modules_s88
  docs/user_manual/UML/control_modules_s88.uxf
  docs/user_manual/images/control_modules_s88.svg
Labels: documentation, enhancement

#1317 [manual] Fix comment
  docs/user_manual/UML/control_modules_s88.uxf
  docs/user_manual/images/control_modules_s88.svg
Labels: documentation, bugfix

#1318 Fix issues discovered by Sonar
  src/Device/DeviceManager.cs
  src/IO/IOManager.cs
  src/TechObject/Base/BaseParameter.cs
  src/TechObject/ObjectsTree/ProcessCell.cs
  src/TechObject/TechObjectManager.cs
Labels: bugfix, safe to test

#1319 [manual] Fix contact way
  ReadMe.md
  docs/de/readme.md
  docs/ru/readme.md
Labels: documentation, bugfix, safe to test
