Repository savushkin-r-d/EasyEPLANner, pull requests merged in 2024-06, with the labels that each got.

#1385 Fix binding attached objects in generic
  src/TechObject/ObjectsTree/UniversalObject/AttachedObjects.cs
Labels: bugfix

#1388 Fix edit new operations created by generic
  src/TechObject/ObjectsTree/UniversalObject/ModesManager.cs
Labels: bugfix

#1393 Add transition to state STOP -> IDLE
  EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/Step.Test.cs
  src/TechObject/ObjectsTree/UniversalObject/Step.cs
Labels: enhancement, bugfix

#1390 Fix update on generic action parameter
  EasyEplanner.Tests/TechObject.Test/Base.Test/Properties.Test/ActionParameter.Test.cs
  src/Editor/ObjectProperty.cs
  src/TechObject/Base/Properties/ActionParameter.cs
  src/TechObject/ObjectsTree/UniversalObject/Actions/ActionWash.cs
Labels: bugfix

#1380 Add new device G
  EasyEplanner.Tests/EplanDevice.Test/IODevice.Test/G.Test.cs
  docs/user_manual/ReadMe.md
  src/Device/DeviceManager.cs
  src/Device/DeviceSubTypeEnum.cs
  src/Device/DeviceTypeEnum.cs
  src/Device/IODevices/G.cs
  src/EasyEPlanner.csproj
Labels: safe to test
